<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250321103248 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE depots CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'Уникальный идентификатор депо\', CHANGE name name VARCHAR(100) NOT NULL COMMENT \'Название депо\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'Дата и время создания записи\', CHANGE updated_at updated_at DATETIME DEFAULT NULL COMMENT \'Дата и время последнего обновления записи\'');
        $this->addSql('ALTER TABLE devices CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'Уникальный идентификатор устройства\', CHANGE depot_id depot_id INT DEFAULT NULL COMMENT \'Идентификатор депо, к которому привязано устройство\', CHANGE name name VARCHAR(100) NOT NULL COMMENT \'Название устройства\', CHANGE type type VARCHAR(50) NOT NULL COMMENT \'Тип устройства (например, радиостанция, носитель информации)\', CHANGE serial_number serial_number VARCHAR(50) NOT NULL COMMENT \'Серийный номер устройства\', CHANGE qr_code qr_code VARCHAR(100) DEFAULT NULL COMMENT \'QR-код или штрих-код устройства\', CHANGE status status VARCHAR(20) NOT NULL COMMENT \'Текущий статус устройства (доступно, выдано, неисправно, в ремонте, списано)\', CHANGE write_off_comment write_off_comment LONGTEXT DEFAULT NULL COMMENT \'Комментарий о причине списания устройства\', CHANGE write_off_date write_off_date DATETIME DEFAULT NULL COMMENT \'Дата списания устройства\', CHANGE repair_comment repair_comment LONGTEXT DEFAULT NULL COMMENT \'Комментарий о ремонте устройства\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'Дата и время создания записи\', CHANGE updated_at updated_at DATETIME DEFAULT NULL COMMENT \'Дата и время последнего обновления записи\'');
        $this->addSql('ALTER TABLE employees CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'Уникальный идентификатор сотрудника\', CHANGE depot_id depot_id INT DEFAULT NULL COMMENT \'Идентификатор депо, к которому привязан сотрудник\', CHANGE full_name full_name VARCHAR(100) NOT NULL COMMENT \'ФИО сотрудника\', CHANGE position position VARCHAR(100) NOT NULL COMMENT \'Должность сотрудника\', CHANGE department department VARCHAR(100) DEFAULT NULL COMMENT \'Подразделение или отдел сотрудника\', CHANGE phone phone VARCHAR(20) DEFAULT NULL COMMENT \'Контактный телефон сотрудника\', CHANGE email email VARCHAR(100) DEFAULT NULL COMMENT \'Электронная почта сотрудника\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'Дата и время создания записи\', CHANGE updated_at updated_at DATETIME DEFAULT NULL COMMENT \'Дата и время последнего обновления записи\', CHANGE deleted_at deleted_at DATETIME DEFAULT NULL COMMENT \'Дата и время удаления записи (если запись удалена)\'');
        $this->addSql('ALTER TABLE logs CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'Уникальный идентификатор записи лога\', CHANGE user_id user_id INT NOT NULL COMMENT \'Идентификатор пользователя, выполнившего операцию\', CHANGE device_id device_id INT DEFAULT NULL COMMENT \'Идентификатор устройства (необязательно)\', CHANGE action action VARCHAR(100) NOT NULL COMMENT \'Описание действия (например, "Выдача устройства", "Возврат устройства")\', CHANGE details details LONGTEXT DEFAULT NULL COMMENT \'Дополнительные детали операции (например, серийный номер устройства, ФИО сотрудника)\', CHANGE details_meta details_meta JSON DEFAULT NULL COMMENT \'Мета-информация об операции в формате JSON (например, дополнительные параметры операции)\', CHANGE timestamp timestamp DATETIME NOT NULL COMMENT \'Дата и время выполнения операции\'');
        $this->addSql('ALTER TABLE transactions CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'Уникальный идентификатор операции\', CHANGE device_id device_id INT NOT NULL COMMENT \'Идентификатор устройства\', CHANGE employee_id employee_id INT NOT NULL COMMENT \'Идентификатор сотрудника, которому выдано устройство\', CHANGE issued_by_id issued_by_id INT NOT NULL COMMENT \'Идентификатор пользователя, который выдал устройство\', CHANGE issued_at issued_at DATETIME NOT NULL COMMENT \'Дата и время выдачи устройства\', CHANGE returned_at returned_at DATETIME DEFAULT NULL COMMENT \'Дата и время возврата устройства\', CHANGE due_date due_date DATETIME NOT NULL COMMENT \'Срок возврата устройства\', CHANGE return_status return_status VARCHAR(20) DEFAULT NULL COMMENT \'Статус возврата (исправно, неисправно, невозвращено)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'Дата и время создания записи\', CHANGE updated_at updated_at DATETIME DEFAULT NULL COMMENT \'Дата и время последнего обновления записи\'');
        $this->addSql('ALTER TABLE users CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'Уникальный идентификатор пользователя\', CHANGE depot_id depot_id INT DEFAULT NULL COMMENT \'Идентификатор депо, к которому привязан пользователь\', CHANGE username username VARCHAR(50) NOT NULL COMMENT \'Логин пользователя\', CHANGE password password VARCHAR(255) NOT NULL COMMENT \'Хэшированный пароль пользователя\', CHANGE role role VARCHAR(20) NOT NULL COMMENT \'Роль пользователя (оператор или администратор)\', CHANGE created_at created_at DATETIME NOT NULL COMMENT \'Дата и время создания учетной записи\', CHANGE updated_at updated_at DATETIME DEFAULT NULL COMMENT \'Дата и время последнего обновления учетной записи\', CHANGE last_login_at last_login_at DATETIME DEFAULT NULL COMMENT \'Дата и время последнего входа в систему\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE depots CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(100) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE users CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE depot_id depot_id INT DEFAULT NULL, CHANGE username username VARCHAR(50) NOT NULL, CHANGE password password VARCHAR(255) NOT NULL, CHANGE role role VARCHAR(20) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE last_login_at last_login_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE devices CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE depot_id depot_id INT DEFAULT NULL, CHANGE name name VARCHAR(100) NOT NULL, CHANGE type type VARCHAR(50) NOT NULL, CHANGE serial_number serial_number VARCHAR(50) NOT NULL, CHANGE qr_code qr_code VARCHAR(100) DEFAULT NULL, CHANGE status status VARCHAR(20) NOT NULL, CHANGE write_off_comment write_off_comment LONGTEXT DEFAULT NULL, CHANGE write_off_date write_off_date DATETIME DEFAULT NULL, CHANGE repair_comment repair_comment LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE transactions CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE device_id device_id INT NOT NULL, CHANGE employee_id employee_id INT NOT NULL, CHANGE issued_by_id issued_by_id INT NOT NULL, CHANGE issued_at issued_at DATETIME NOT NULL, CHANGE returned_at returned_at DATETIME DEFAULT NULL, CHANGE due_date due_date DATETIME NOT NULL, CHANGE return_status return_status VARCHAR(20) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE logs CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE device_id device_id INT DEFAULT NULL, CHANGE action action VARCHAR(100) NOT NULL, CHANGE details details LONGTEXT DEFAULT NULL, CHANGE details_meta details_meta JSON DEFAULT NULL, CHANGE timestamp timestamp DATETIME NOT NULL');
        $this->addSql('ALTER TABLE employees CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE depot_id depot_id INT DEFAULT NULL, CHANGE full_name full_name VARCHAR(100) NOT NULL, CHANGE position position VARCHAR(100) NOT NULL, CHANGE department department VARCHAR(100) DEFAULT NULL, CHANGE phone phone VARCHAR(20) DEFAULT NULL, CHANGE email email VARCHAR(100) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE deleted_at deleted_at DATETIME DEFAULT NULL');
    }
}
